import { useEffect, useState, useMemo } from 'react';
import { QuickPlanSheet } from '@/components/plans/QuickPlanSheet';
import { useAuth } from '@/hooks/useAuth';
import { useParams, Link, useSearchParams, useNavigate } from 'react-router-dom';
import { format, addDays, addWeeks, startOfWeek, isSameDay, isToday, isSameWeek } from 'date-fns';
import { Sparkles, Calendar, Home, Building2, Car, Loader2, Clock, MapPin, Send, X, ChevronLeft, ChevronRight, ChevronDown, Plane, ArrowLeft } from 'lucide-react';
import { cn } from '@/lib/utils';
import { supabase } from '@/integrations/supabase/client';
import { iosSupabase } from '@/integrations/supabase/iosClient';
import { TIME_SLOT_LABELS, TimeSlot, VIBE_CONFIG, VibeType, ACTIVITY_CONFIG } from '@/types/planner';
import { ParadeWordmark } from '@/components/ui/ParadeWordmark';
import { ElephantLoader } from '@/components/ui/ElephantLoader';
import { MobileNav } from '@/components/layout/MobileNav';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { toast } from 'sonner';
import { AvailabilityPills } from '@/components/share/AvailabilityPills';

interface ProfileData {
  user_id: string | null;
  display_name: string | null;
  avatar_url: string | null;
  current_vibe: string | null;
  custom_vibe_tags: string[] | null;
  location_status: string | null;
  default_work_days: string[] | null;
  default_work_start_hour: number | null;
  default_work_end_hour: number | null;
  default_availability_status: string | null;
}

interface AvailabilityData {
  date: string;
  early_morning: boolean | null;
  late_morning: boolean | null;
  early_afternoon: boolean | null;
  late_afternoon: boolean | null;
  evening: boolean | null;
  late_night: boolean | null;
  location_status: string | null;
  trip_location: string | null;
}

interface PlanData {
  id: string;
  title: string;
  activity: string;
  date: string;
  time_slot: string;
  duration: number;
  location: string | null;
}

interface SelectedSlot {
  day: Date;
  dayLabel: string;
  slot: TimeSlot;
  slotLabel: string;
}

const LOCATION_CONFIG = {
  home: { label: 'At Home', icon: Home, color: 'text-blue-500' },
  office: { label: 'At Office', icon: Building2, color: 'text-purple-500' },
  traveling: { label: 'Traveling', icon: Car, color: 'text-availability-away-foreground' },
};

// Map time slots to hour ranges for default work schedule calculation
const TIME_SLOT_HOURS: Record<TimeSlot, { start: number; end: number }> = {
  'early-morning': { start: 6, end: 9 },
  'late-morning': { start: 9, end: 12 },
  'early-afternoon': { start: 12, end: 15 },
  'late-afternoon': { start: 15, end: 18 },
  'evening': { start: 18, end: 21 },
  'late-night': { start: 21, end: 24 },
};

export default function Share() {
  const { shareCode } = useParams<{ shareCode: string }>();
  const { user } = useAuth();
  const [searchParams] = useSearchParams();
  const [profile, setProfile] = useState<ProfileData | null>(null);
  const [availability, setAvailability] = useState<AvailabilityData[]>([]);
  const [myAvailability, setMyAvailability] = useState<AvailabilityData[]>([]);
  const [plans, setPlans] = useState<PlanData[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  
  // Hang request state
  const [selectedSlot, setSelectedSlot] = useState<SelectedSlot | null>(null);
  const [requestDialogOpen, setRequestDialogOpen] = useState(false);
  const [requesterName, setRequesterName] = useState('');
  const [requesterEmail, setRequesterEmail] = useState('');
  const [requestMessage, setRequestMessage] = useState('');
  const [sendingRequest, setSendingRequest] = useState(false);
  const [quickPlanOpen, setQuickPlanOpen] = useState(false);
  
  // Week navigation state — max offset depends on view param
  const viewParam = searchParams.get('view') || '3m';
  const maxWeekOffset = viewParam === '3m' ? 12 : viewParam === '1m' ? 4 : 0;
  // Links generated by the native iOS app carry `?src=ios`; their data lives
  // in the iOS Supabase project, so route the public reads there.
  const shareClient = searchParams.get('src') === 'ios' ? iosSupabase : supabase;
  const [weekOffset, setWeekOffset] = useState(0);
  const [expandedDays, setExpandedDays] = useState<Set<string>>(new Set());
  const [viewMode, setViewMode] = useState<'pills' | 'grid'>('pills');

  const toggleDay = (key: string) => {
    setExpandedDays(prev => {
      const next = new Set(prev);
      if (next.has(key)) next.delete(key);
      else next.add(key);
      return next;
    });
  };

  // Get week days based on offset (Monday to Sunday)
  const weekDays = useMemo(() => {
    const start = startOfWeek(addWeeks(new Date(), weekOffset), { weekStartsOn: 1 });
    return Array.from({ length: 7 }, (_, i) => addDays(start, i));
  }, [weekOffset]);
  
  const isCurrentWeek = isSameWeek(weekDays[0], new Date(), { weekStartsOn: 1 });

  useEffect(() => {
    const fetchData = async () => {
      if (!shareCode) {
        setError('No share code specified');
        setLoading(false);
        return;
      }

      try {
        // Fetch profile by share_code using security definer function
        const { data: profileRows, error: profileError } = await shareClient
          .rpc('get_profile_by_share_code', { p_share_code: shareCode });

        const profileData = profileRows?.[0] ?? null;

        if (profileError || !profileData) {
          setError('This share link is not valid');
          setLoading(false);
          return;
        }

        setProfile(profileData);

        // Fetch availability for the week using security definer function
        const startDate = format(weekDays[0], 'yyyy-MM-dd');
        const endDate = format(weekDays[6], 'yyyy-MM-dd');

        const { data: availData } = await shareClient
          .rpc('get_availability_by_share_code', {
            p_share_code: shareCode,
            p_start_date: startDate,
            p_end_date: endDate,
          });

        setAvailability(availData || []);

        // Fetch current user's availability for overlap detection
        if (user) {
          const { data: myAvailData } = await supabase
            .from('availability')
            .select('date, early_morning, late_morning, early_afternoon, late_afternoon, evening, late_night, location_status, trip_location')
            .eq('user_id', user.id)
            .gte('date', startDate)
            .lte('date', endDate);
          setMyAvailability(myAvailData || []);
        }

        // Fetch plans for the week using security definer function
        const { data: plansData } = await shareClient
          .rpc('get_plans_by_share_code', {
            p_share_code: shareCode,
            p_start_date: weekDays[0].toISOString(),
            p_end_date: weekDays[6].toISOString(),
          });

        setPlans(plansData || []);
      } catch (err) {
        console.error('Error fetching share data:', err);
        setError('Failed to load availability');
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, [shareCode, weekDays, shareClient]);

  // Check if a slot is busy based on work schedule defaults
  const isDefaultBusy = (date: Date, slot: TimeSlot): boolean => {
    if (!profile) return false;
    const workDays = profile.default_work_days || ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'];
    const dayOfWeek = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'][date.getDay()];
    const isWorkDay = workDays.includes(dayOfWeek);
    
    if (!isWorkDay) return false;
    
    const workStart = profile.default_work_start_hour ?? 9;
    const workEnd = profile.default_work_end_hour ?? 17;
    const hours = TIME_SLOT_HOURS[slot];
    
    return hours.start < workEnd && hours.end > workStart;
  };

  const getSlotStatus = (date: Date, slot: TimeSlot): 'available' | 'busy' | 'plan' => {
    // Check if there's a plan during this slot
    const hasPlan = plans.some(
      (p) => isSameDay(new Date(p.date), date) && p.time_slot === slot
    );
    
    if (hasPlan) return 'plan';
    
    // Check availability setting
    const dateStr = format(date, 'yyyy-MM-dd');
    const dayAvail = availability.find((a) => a.date === dateStr);
    
    if (!dayAvail) {
      // No explicit availability row — apply work schedule defaults
      const defaultFree = profile?.default_availability_status !== 'unavailable';
      if (!defaultFree) return 'busy';
      return isDefaultBusy(date, slot) ? 'busy' : 'available';
    }
    
    const slotMap: Record<TimeSlot, keyof AvailabilityData> = {
      'early-morning': 'early_morning',
      'late-morning': 'late_morning',
      'early-afternoon': 'early_afternoon',
      'late-afternoon': 'late_afternoon',
      'evening': 'evening',
      'late-night': 'late_night',
    };
    
    return dayAvail[slotMap[slot]] === false ? 'busy' : 'available';
  };

  const isMySlotFree = (date: Date, slot: TimeSlot): boolean => {
    if (!user) return false;
    const dateStr = format(date, 'yyyy-MM-dd');
    const dayAvail = myAvailability.find((a) => a.date === dateStr);
    if (!dayAvail) return true; // Default to available
    const slotMap: Record<TimeSlot, keyof AvailabilityData> = {
      'early-morning': 'early_morning',
      'late-morning': 'late_morning',
      'early-afternoon': 'early_afternoon',
      'late-afternoon': 'late_afternoon',
      'evening': 'evening',
      'late-night': 'late_night',
    };
    return dayAvail[slotMap[slot]] !== false;
  };

  const getDayAvailabilityScore = (date: Date): number => {
    const slots = Object.keys(TIME_SLOT_LABELS) as TimeSlot[];
    const availableSlots = slots.filter(
      (slot) => getSlotStatus(date, slot) === 'available'
    ).length;
    return availableSlots / slots.length;
  };

  const handleSlotClick = (day: Date, slot: TimeSlot) => {
    if (user && profile?.user_id) {
      // Logged-in user: open QuickPlanSheet
      setSelectedSlot({
        day,
        dayLabel: format(day, 'EEEE, MMM d'),
        slot,
        slotLabel: TIME_SLOT_LABELS[slot].label,
      });
      setQuickPlanOpen(true);
    } else {
      // Non-logged-in: show the old request dialog
      setSelectedSlot({
        day,
        dayLabel: format(day, 'EEEE, MMM d'),
        slot,
        slotLabel: TIME_SLOT_LABELS[slot].label,
      });
      setRequestDialogOpen(true);
    }
  };

  const handleSendRequest = async () => {
    if (!requesterName.trim() || !selectedSlot || !shareCode) {
      toast.error('Please enter your name');
      return;
    }

    setSendingRequest(true);

    try {
      const response = await shareClient.functions.invoke('send-hang-request', {
        body: {
          shareCode,
          requesterName: requesterName.trim(),
          requesterEmail: requesterEmail.trim() || undefined,
          message: requestMessage.trim() || undefined,
          selectedDay: format(selectedSlot.day, 'yyyy-MM-dd'),
          selectedDayLabel: selectedSlot.dayLabel,
          selectedSlot: selectedSlot.slot,
          selectedSlotLabel: selectedSlot.slotLabel,
        },
      });

      if (response.error) {
        throw new Error(response.error.message || 'Failed to send request');
      }

      toast.success(`Request sent to ${profile?.display_name || 'user'}!`, {
        description: "They'll get an email with your request.",
      });
      
      setRequestDialogOpen(false);
      setRequesterName('');
      setRequesterEmail('');
      setRequestMessage('');
      setSelectedSlot(null);
    } catch (err) {
      console.error('Error sending hang request:', err);
      toast.error("Couldn't send that — try again?", {
        description: 'Give it another shot in a moment.',
      });
    } finally {
      setSendingRequest(false);
    }
  };

  const getPlansForDay = (date: Date): PlanData[] => {
    return plans.filter((p) => isSameDay(new Date(p.date), date));
  };

  // Get upcoming plans (today and future)
  const upcomingPlans = useMemo(() => {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    return plans
      .filter((p) => new Date(p.date) >= today)
      .slice(0, 5);
  }, [plans]);

  if (loading) {
    return <ElephantLoader />;
  }

  if (error || !profile) {
    return (
      <div className="flex min-h-screen flex-col items-center justify-center gap-4 bg-gradient-to-br from-background via-background to-primary/5 p-6">
        <div className="rounded-2xl bg-card p-8 text-center shadow-lg">
          <h1 className="font-display text-2xl font-bold text-foreground">
            {error || 'User not found'}
          </h1>
          <p className="mt-2 text-muted-foreground">
            This availability page is not available.
          </p>
          {!user && (
            <Link
              to="/landing"
              className="mt-6 inline-block rounded-full bg-primary px-6 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90"
            >
              Get Parade
            </Link>
          )}
        </div>
      </div>
    );
  }

  const locationConfig = profile.location_status
    ? LOCATION_CONFIG[profile.location_status as keyof typeof LOCATION_CONFIG]
    : null;
  const LocationIcon = locationConfig?.icon;

  const vibeConfig = profile.current_vibe
    ? VIBE_CONFIG[profile.current_vibe as VibeType]
    : null;

  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-background to-primary/5">
      {/* Header */}
      <header className="border-b border-border/50 bg-card/50 backdrop-blur-sm">
        <div className="mx-auto flex max-w-2xl items-center justify-between px-4 py-3">
          <div className="flex items-center gap-2">
            {user && (
              <Button
                variant="ghost"
                size="icon"
                className="h-8 w-8 shrink-0"
                onClick={() => window.history.length > 1 ? window.history.back() : window.location.href = '/availability'}
              >
                <ArrowLeft className="h-4 w-4" />
              </Button>
            )}
            <ParadeWordmark size="md" />
          </div>
          {!user && (
            <Link
              to="/landing"
              className="rounded-full bg-primary px-4 py-1.5 text-sm font-medium text-primary-foreground hover:bg-primary/90"
            >
              Get Parade
            </Link>
          )}
        </div>
      </header>

      <main className={cn("mx-auto max-w-2xl px-4 py-4 space-y-4", user && "pb-24")}>
        {/* Profile Card */}
        <div className="rounded-2xl bg-card p-4 shadow-soft">
          <div className="flex items-center gap-3">
            <div className="h-12 w-12 overflow-hidden rounded-full bg-primary/10">
              {profile.avatar_url ? (
                <img
                  src={profile.avatar_url}
                  alt={profile.display_name || 'User'}
                  className="h-full w-full object-cover"
                />
              ) : (
                <div className="flex h-full w-full items-center justify-center text-xl font-bold text-primary">
                  {(profile.display_name || 'U')[0].toUpperCase()}
                </div>
              )}
            </div>
            <div>
              <h1 className="font-display text-xl font-bold">
                {(profile.display_name?.split(' ')[0]) || 'User'}'s Week
              </h1>
              <p className="text-sm text-muted-foreground">See what I'm up to!</p>
            </div>
          </div>

          {/* Status Row */}
          {(locationConfig || vibeConfig || (profile.current_vibe === 'custom' && profile.custom_vibe_tags?.length)) && (
            <div className="mt-3 flex flex-wrap gap-2">
              {/* Location Status */}
              {locationConfig && LocationIcon && (
                <div className="flex items-center gap-1.5 rounded-full bg-muted/50 px-2.5 py-1">
                  <LocationIcon className={cn('h-3.5 w-3.5', locationConfig.color)} />
                  <span className="text-xs font-medium">{locationConfig.label}</span>
                </div>
              )}

              {/* Vibe Status */}
              {vibeConfig && (
                <div className="flex items-center gap-1.5 rounded-full bg-muted/50 px-2.5 py-1">
                  <vibeConfig.icon className="h-3.5 w-3.5" />
                  <span className="text-xs font-medium">{vibeConfig.label}</span>
                </div>
              )}

              {/* Custom Vibe Tags */}
              {profile.current_vibe === 'custom' &&
                profile.custom_vibe_tags?.map((tag) => (
                  <div
                    key={tag}
                    className="flex items-center gap-1 rounded-full bg-gradient-to-r from-primary/10 to-secondary/10 px-2.5 py-1"
                  >
                    <Sparkles className="h-3 w-3 text-primary" />
                    <span className="text-xs font-medium">#{tag}</span>
                  </div>
                ))}
            </div>
          )}
        </div>

        {/* Week Overview — matching dashboard style */}
        <div className="rounded-2xl border border-border bg-card p-4 shadow-soft">
          <div className="mb-3 flex items-center justify-between">
            <div className="flex items-center gap-1">
              <Button
                variant="ghost"
                size="icon"
                className="h-7 w-7"
                onClick={() => setWeekOffset(prev => prev - 1)}
                disabled={weekOffset <= 0}
              >
                <ChevronLeft className="h-4 w-4" />
              </Button>
              <span className="text-xs font-medium min-w-[80px] text-center text-muted-foreground">
                {weekOffset === 0 ? 'This Week' : weekOffset === 1 ? 'Next Week' : `${format(weekDays[0], 'MMM d')} – ${format(weekDays[6], 'MMM d')}`}
              </span>
              <Button
                variant="ghost"
                size="icon"
                className="h-7 w-7"
                onClick={() => setWeekOffset(prev => prev + 1)}
                disabled={weekOffset >= maxWeekOffset}
              >
                <ChevronRight className="h-4 w-4" />
              </Button>
              {!isCurrentWeek && (
                <Button
                  variant="ghost"
                  size="sm"
                  className="text-xs text-primary h-6 px-2"
                  onClick={() => setWeekOffset(0)}
                >
                  ← Back to this week
                </Button>
              )}
            </div>
            {isCurrentWeek && (
              <span className="text-xs text-muted-foreground">
                {format(weekDays[0], 'MMM d')} – {format(weekDays[6], 'MMM d')}
              </span>
            )}
          </div>

          {/* Legend + view toggle */}
          <div className="flex items-center justify-between gap-2 text-[10px] text-muted-foreground mb-2">
            <div className="flex items-center gap-3 min-w-0">
              {user ? (
                <>
                  <div className="flex items-center gap-1">
                    <span className="h-2 w-2 rounded-full bg-availability-available" />
                    <span>Both free</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <span className="h-2 w-2 rounded-full bg-availability-available/40" />
                    <span className="truncate">Only {profile?.display_name?.split(' ')[0] || 'them'} free</span>
                  </div>
                </>
              ) : (
                <>
                  <div className="flex items-center gap-1">
                    <span className="h-1 w-4 rounded-full bg-availability-available/60" />
                    <span>Free</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <span className="h-1 w-4 rounded-full bg-muted-foreground/20" />
                    <span>Busy</span>
                  </div>
                </>
              )}
            </div>
            <button
              type="button"
              onClick={() => setViewMode(viewMode === 'pills' ? 'grid' : 'pills')}
              className="shrink-0 rounded-full bg-muted/60 px-2 py-0.5 text-[10px] font-medium text-foreground hover:bg-muted transition-colors"
            >
              {viewMode === 'pills' ? 'Detailed view' : 'Pills view'}
            </button>
          </div>


          {viewMode === 'pills' ? (
            <AvailabilityPills
              days={weekDays}
              getSlotStatus={getSlotStatus}
              isMySlotFree={user ? isMySlotFree : undefined}
              plans={plans}
              dayMeta={Object.fromEntries(
                availability.map((a) => [
                  a.date,
                  { isAway: a.location_status === 'away', trip_location: a.trip_location },
                ]),
              )}
              signedIn={!!user}
              onSlotClick={handleSlotClick}
            />
          ) : (() => {
            const SLOTS = Object.keys(TIME_SLOT_LABELS) as TimeSlot[];
            const today0 = new Date(new Date().setHours(0, 0, 0, 0));

            const daySummary = (day: Date) => {
              const dateStr = format(day, 'yyyy-MM-dd');
              const dayAvail = availability.find((a) => a.date === dateStr);
              const isAway = dayAvail?.location_status === 'away';
              const free = SLOTS.filter((s) => getSlotStatus(day, s) === 'available').length;
              const planCount = SLOTS.filter((s) => getSlotStatus(day, s) === 'plan').length;
              return { dayAvail, isAway, free, planCount, total: SLOTS.length };
            };

            const renderSlotBars = (day: Date) => (
              <div className="flex gap-0.5">
                {SLOTS.map((slot) => {
                  const status = getSlotStatus(day, slot);
                  const bothFree = status === 'available' && user && isMySlotFree(day, slot);
                  return (
                    <div
                      key={slot}
                      className={cn(
                        'h-1 flex-1 rounded-full',
                        status === 'available' && bothFree && 'bg-availability-available',
                        status === 'available' && !bothFree && 'bg-availability-available/40',
                        status === 'plan' && 'bg-primary/60',
                        status === 'busy' && 'bg-muted-foreground/20',
                      )}
                    />
                  );
                })}
              </div>
            );

            const renderExpandedSlots = (day: Date) => {
              const dayPlans = getPlansForDay(day);
              return (
                <div className="space-y-0.5 animate-fade-in pt-1">
                  {SLOTS.map((slot) => {
                    const status = getSlotStatus(day, slot);
                    const isAvailable = status === 'available';
                    const bothFree = isAvailable && user && isMySlotFree(day, slot);
                    const slotInfo = TIME_SLOT_LABELS[slot];
                    const slotPlans = dayPlans.filter((p) => p.time_slot === slot);
                    return (
                      <button
                        key={slot}
                        disabled={!isAvailable}
                        onClick={() => isAvailable && handleSlotClick(day, slot)}
                        className={cn(
                          'flex w-full items-center gap-1.5 rounded-md px-2 py-1 text-[11px] transition-colors text-left',
                          isAvailable && bothFree && 'bg-availability-available/30 text-foreground hover:bg-availability-available/40 cursor-pointer ring-1 ring-availability-available/30',
                          isAvailable && !bothFree && 'bg-availability-available/15 text-foreground hover:bg-availability-available/25 cursor-pointer',
                          status === 'plan' && 'bg-muted/60 text-foreground cursor-not-allowed',
                          status === 'busy' && 'bg-muted/30 text-muted-foreground cursor-not-allowed',
                        )}
                      >
                        <span
                          className={cn(
                            'h-1.5 w-1.5 shrink-0 rounded-full',
                            isAvailable && bothFree && 'bg-availability-available',
                            isAvailable && !bothFree && 'bg-availability-available/50',
                            status === 'plan' && 'bg-primary',
                            status === 'busy' && 'bg-muted-foreground/40',
                          )}
                        />
                        <span className="font-medium truncate">{slotInfo.label}</span>
                        <span className="text-muted-foreground ml-auto text-[9px] shrink-0">{slotInfo.time}</span>
                        {slotPlans.length > 0 && (
                          <span className="shrink-0 text-[9px]">
                            {(() => {
                              const cfg = ACTIVITY_CONFIG[slotPlans[0].activity as keyof typeof ACTIVITY_CONFIG];
                              return cfg?.icon || '📅';
                            })()}
                          </span>
                        )}
                        {isAvailable && <Send className="h-2.5 w-2.5 shrink-0 text-availability-available/60" />}
                      </button>
                    );
                  })}
                </div>
              );
            };

            const renderAwayLocation = (sum: ReturnType<typeof daySummary>, max = 70) =>
              sum.isAway ? (
                <span className="flex items-center gap-1 text-availability-away font-medium">
                  <Plane className="h-2.5 w-2.5 shrink-0" />
                  {sum.dayAvail?.trip_location && (
                    <span className={`truncate max-w-[${max}px]`}>{sum.dayAvail.trip_location}</span>
                  )}
                </span>
              ) : (
                <span className="flex items-center gap-1 text-muted-foreground">
                  <Home className="h-2.5 w-2.5 shrink-0" />
                </span>
              );

            const sat = weekDays[5];
            const sun = weekDays[6];
            const sameMonth = sat.getMonth() === sun.getMonth();
            const weekendDateLabel = sameMonth
              ? `${format(sat, 'EEE d')} – ${format(sun, 'EEE d')}`
              : `${format(sat, 'MMM d')} – ${format(sun, 'MMM d')}`;
            const satSum = daySummary(sat);
            const sunSum = daySummary(sun);
            const weekendAway = satSum.isAway || sunSum.isAway;
            const weekendPlanCount = satSum.planCount + sunSum.planCount;
            const weekendHeadline = weekendAway
              ? 'Away this weekend'
              : weekendPlanCount > 0
                ? 'Weekend lineup'
                : 'Open weekend';

            const renderWeekendMini = (day: Date, sum: ReturnType<typeof daySummary>) => {
              const isPastDay = day < today0;
              const key = day.toISOString();
              const isExpanded = expandedDays.has(key);
              return (
                <div key={key} className={cn('rounded-xl border border-border/60 bg-background/60 p-2.5', isPastDay && 'opacity-50')}>
                  <button
                    onClick={() => !isPastDay && toggleDay(key)}
                    disabled={isPastDay}
                    className="w-full text-left"
                  >
                    <div className="flex items-baseline gap-1.5">
                      <span className="font-display text-2xl font-black leading-none">{format(day, 'd')}</span>
                      <span className="text-sm font-semibold text-muted-foreground">{format(day, 'EEE')}</span>
                      {isToday(day) && (
                        <span className="ml-auto rounded-full bg-primary/10 px-1.5 py-0.5 text-[9px] font-medium text-primary">Today</span>
                      )}
                    </div>
                    <div className="mt-2">{renderSlotBars(day)}</div>
                    <div className="mt-1.5 flex items-center justify-between text-[10px]">
                      <span className={cn('font-medium', sum.free / sum.total >= 0.5 ? 'text-availability-available' : 'text-muted-foreground')}>
                        {sum.free}/{sum.total} free{sum.planCount > 0 && ` · ${sum.planCount} plan${sum.planCount === 1 ? '' : 's'}`}
                      </span>
                      {renderAwayLocation(sum, 60)}
                    </div>
                  </button>
                  {isExpanded && !isPastDay && renderExpandedSlots(day)}
                </div>
              );
            };

            return (
              <div className="space-y-2">
                {/* Weekend hero — Sat + Sun */}
                <section
                  className={cn(
                    'relative overflow-hidden rounded-2xl border p-4',
                    weekendAway
                      ? 'border-availability-away/30 bg-gradient-to-br from-availability-away/15 via-card to-secondary/10'
                      : 'border-border bg-card',
                  )}
                >
                  <div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-wider">
                    <span className="h-1.5 w-1.5 rounded-full bg-secondary" />
                    <span className="text-secondary">This Weekend</span>
                    <span className="font-medium normal-case tracking-normal text-muted-foreground">{weekendDateLabel}</span>
                  </div>
                  <h2 className="mt-2 font-display text-2xl font-black leading-tight tracking-tight">
                    {weekendAway && <Plane className="mr-1 inline-block h-5 w-5 align-[-2px] text-availability-away" />}
                    {weekendHeadline}
                  </h2>
                  <div className="mt-3 grid grid-cols-2 gap-2.5">
                    {renderWeekendMini(sat, satSum)}
                    {renderWeekendMini(sun, sunSum)}
                  </div>
                </section>

                {/* Weekday rows — Mon..Fri */}
                {weekDays.slice(0, 5).map((day) => {
                  const key = day.toISOString();
                  const isTodayDay = isToday(day);
                  const isPastDay = day < today0;
                  const isExpanded = expandedDays.has(key);
                  const sum = daySummary(day);
                  const score = sum.free / sum.total;
                  const summaryLabel =
                    score >= 0.8 ? 'Open' :
                    score >= 0.5 ? 'Mostly Open' :
                    score >= 0.2 ? 'Some time' : 'Booked';
                  const summaryPillClass =
                    score >= 0.8 ? 'bg-availability-available/25 text-[hsl(152_55%_22%)] dark:text-[hsl(152_50%_55%)]' :
                    score >= 0.5 ? 'bg-availability-available/10 text-[hsl(152_35%_42%)] dark:text-[hsl(152_45%_70%)]' :
                    score >= 0.2 ? 'bg-amber-200/60 text-amber-800 dark:bg-amber-500/20 dark:text-amber-300' :
                    'bg-secondary/15 text-secondary';

                  return (
                    <div key={key} className={cn(isPastDay && 'opacity-50')}>
                      <button
                        onClick={() => !isPastDay && toggleDay(key)}
                        disabled={isPastDay}
                        className={cn(
                          'group relative flex w-full items-center gap-3 rounded-2xl px-3 py-3 text-left transition-colors',
                          'border border-border bg-card',
                          !isPastDay && 'hover:bg-card/80',
                          isTodayDay && 'ring-1 ring-primary/20 border-primary',
                          sum.isAway && 'bg-availability-away/10',
                        )}
                      >
                        {/* Date block */}
                        <div className="shrink-0 flex h-12 w-12 flex-col items-center justify-center rounded-xl bg-muted/40 text-center">
                          <span className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
                            {format(day, 'EEE')}
                          </span>
                          <span className="font-display text-xl font-black leading-none">{format(day, 'd')}</span>
                        </div>

                        {/* Status + slot bars */}
                        <div className="min-w-0 flex-1">
                          <div className="flex items-baseline gap-1.5 flex-wrap">
                            <span className={cn('inline-flex items-center rounded-full px-2 py-0.5 text-[11px] font-semibold', summaryPillClass)}>
                              {summaryLabel}
                            </span>
                            <span className="text-xs text-muted-foreground">
                              · {sum.free}/{sum.total} free{sum.planCount > 0 && ` · ${sum.planCount} plan${sum.planCount === 1 ? '' : 's'}`}
                            </span>
                            {isTodayDay && (
                              <span className="rounded-full bg-primary/10 px-1.5 py-0.5 text-[9px] font-medium text-primary">Today</span>
                            )}
                          </div>
                          <div className="mt-1.5">{renderSlotBars(day)}</div>
                        </div>

                        {/* Right: location + chevron */}
                        <div className="shrink-0 flex items-center gap-1.5 text-[10px]">
                          {renderAwayLocation(sum)}
                          {!isPastDay && (
                            <ChevronDown className={cn('h-3.5 w-3.5 text-muted-foreground transition-transform', isExpanded && 'rotate-180')} />
                          )}
                        </div>
                      </button>

                      {isExpanded && !isPastDay && (
                        <div className="mt-1 px-3">{renderExpandedSlots(day)}</div>
                      )}
                    </div>
                  );
                })}
              </div>
            );
          })()}

        </div>


        {/* CTA */}
        {!user && (
          <div className="text-center pt-2">
            <p className="mb-3 text-sm text-muted-foreground">
              Want to share your own availability with friends?
            </p>
            <Link
              to="/landing"
              className="inline-flex items-center gap-2 rounded-full bg-primary px-6 py-2.5 font-medium text-primary-foreground shadow-md hover:bg-primary/90"
            >
              <Sparkles className="h-4 w-4" />
              Get Parade - It's Free!
            </Link>
          </div>
        )}
      </main>

      {/* Hang Request Dialog */}
      <Dialog open={requestDialogOpen} onOpenChange={setRequestDialogOpen}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="font-display text-xl">Request to Hang 🎉</DialogTitle>
          </DialogHeader>
          
          <div className="space-y-4 py-4">
            {/* Selected time display */}
            {selectedSlot && (
              <div className="flex items-center gap-3 rounded-lg bg-primary/10 p-3">
                <Calendar className="h-5 w-5 text-primary" />
                <div>
                  <p className="font-medium">{selectedSlot.dayLabel}</p>
                  <p className="text-sm text-muted-foreground">{selectedSlot.slotLabel}</p>
                </div>
              </div>
            )}
            
            <div className="space-y-2">
              <Label htmlFor="requester-name">Your Name *</Label>
              <Input
                id="requester-name"
                placeholder="What's your name?"
                value={requesterName}
                onChange={(e) => setRequesterName(e.target.value)}
                required
              />
            </div>
            
            <div className="space-y-2">
              <Label htmlFor="requester-email">Your Email (optional)</Label>
              <Input
                id="requester-email"
                type="email"
                placeholder="So they can reply to you"
                value={requesterEmail}
                onChange={(e) => setRequesterEmail(e.target.value)}
              />
            </div>
            
            <div className="space-y-2">
              <Label htmlFor="request-message">Message (optional)</Label>
              <Textarea
                id="request-message"
                placeholder="What do you want to do?"
                value={requestMessage}
                onChange={(e) => setRequestMessage(e.target.value)}
                rows={3}
              />
            </div>
            
            <Button 
              onClick={handleSendRequest} 
              disabled={!requesterName.trim() || sendingRequest}
              className="w-full gap-2"
            >
              {sendingRequest ? (
                <>
                  <Loader2 className="h-4 w-4 animate-spin" />
                  Sending...
                </>
              ) : (
                <>
                  <Send className="h-4 w-4" />
                  Send Request to {profile?.display_name || 'User'}
                </>
              )}
            </Button>
            
            <p className="text-xs text-center text-muted-foreground">
              They'll receive an email with your request
            </p>
          </div>
        </DialogContent>
      </Dialog>
      {user && <MobileNav />}

      {profile?.user_id && (
        <QuickPlanSheet
          open={quickPlanOpen}
          onOpenChange={setQuickPlanOpen}
          preSelectedFriend={{
            userId: profile.user_id,
            name: profile.display_name || 'Friend',
            avatar: profile.avatar_url || undefined,
          }}
          preSelectedDate={selectedSlot?.day}
          preSelectedTimeSlot={selectedSlot?.slot}
        />
      )}
    </div>
  );
}
